Feature/#9 home create room
KDS-OurMemory/Server pull request #14
Opened 2021-03-05 10:56 UTC by idean3885

## #9 

## PR 설명
- 방 생성 기능 추가

## 변경된 내용
- 방을 생성하고 사용자-방 관계테이블에 방에 참여하는 사람들을 추가합니다.

## 추가적인 정보
- 현재 관계테이블에 데이터가 추가되지 않는 버그가 있습니다.

2021-03-07 14:13 UTC, HwanChang requested changes
RoomService 에서의 문제를 당장 해결은 할 수 있지만 전체적인 리팩토링을 하면 저 문제는 발생하지 않을 것 같아요.
서비스의 완성도를 위해서는 JPA 활용 부분의 리팩토링을 추천드려요.
기존에 쓰던 UsersAndRooms 테이블같은 연관관계 테이블을 직접 생성하여 관리하기보단 아래 링크에 있는 내용을 활용해보면 깔끔하게 정리가 될 것 같아요.

[연관관계 매핑](https://victorydntmd.tistory.com/208)

Stream API 나 Optional API 사용 관련하여 몇가지 수정할 사항이 있는데 이 부분은 리팩토링이 끝나면 사용을 안하게 될 수도 있어서 추후에 다시 확인해서 리뷰드릴게요.
🙌🙌🙌🙌🙌

2021-03-08 00:36 UTC, idean3885 commented
확인 감사합니다. 알려주신 내용 확인하여 코드 리팩토링하고 다시 말씀드리겠습니다.
감사합니다.

2021-03-08 00:37 UTC, idean3885 commented on OurMemory_Server/src/main/java/com/kds/ourmemory/service/v1/room/RoomService.java
> +                .map(id -> userRepo.findById(id).map(u -> usersAndRoomsRepo.save(new UsersAndRooms(u, room)))).count();
여기서 관계테이블 UsersAndRooms 에 데이터를 세이브하는 경우 아래와 같이 users -> Long 로 세팅할수 없다는 에러가 발생합니다.

org.springframework.dao.InvalidDataAccessApiUsageException: Can not set com.kds.ourmemory.domain.Users field com.kds.ourmemory.domain.UsersAndRoomsPk.user to java.lang.Long

테이블 설정 부분이 미흡한 것 같은데 정확히 어떤 오류인지 확인해주시면 감사하겠습니다.

2021-03-08 08:57 UTC, hwanchang commented on OurMemory_Server/src/main/java/com/kds/ourmemory/service/v1/room/RoomService.java
> +                .map(id -> userRepo.findById(id).map(u -> usersAndRoomsRepo.save(new UsersAndRooms(u, room)))).count();
아래 커밋된 내용으로 수정한 후에도 계속 발생하는 에러인가요??

2021-03-08 09:21 UTC, idean3885 commented on OurMemory_Server/src/main/java/com/kds/ourmemory/service/v1/room/RoomService.java
> +                .map(id -> userRepo.findById(id).map(u -> usersAndRoomsRepo.save(new UsersAndRooms(u, room)))).count();
아래 내용으로 수정한 후에는 정상적으로 처리됩니다! 
이 방식으로 하고 저 일정있는거 끝나고 마저 볼 것 같습니다.

2021-03-08 12:00 UTC, HwanChang commented on OurMemory_Server/src/main/java/com/kds/ourmemory/service/v1/room/RoomService.java
> +                .map(id -> userRepo.findById(id).map(u -> usersAndRoomsRepo.save(new UsersAndRooms(u, room)))).count();
넵 알겠습니다!
나중에 리뷰 필요하시면 말씀해주세요!

2021-03-08 12:46 UTC, idean3885 commented on OurMemory_Server/src/main/java/com/kds/ourmemory/service/v1/room/RoomService.java
> +                .map(id -> userRepo.findById(id).map(u -> usersAndRoomsRepo.save(new UsersAndRooms(u, room)))).count();
네, 알겠습니다!!

2021-03-15 14:14 UTC, merged